# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cardsGame_pb2 as cardsGame__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cardsGame_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CardsGameServerStub(object):
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/cardsGame.CardsGameServer/Connect',
                request_serializer=cardsGame__pb2.ConnectReq.SerializeToString,
                response_deserializer=cardsGame__pb2.ConnectRsp.FromString,
                _registered_method=True)


class CardsGameServerServicer(object):
    """The service definition
    """

    def Connect(self, request, context):
        """A simple RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardsGameServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=cardsGame__pb2.ConnectReq.FromString,
                    response_serializer=cardsGame__pb2.ConnectRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardsGame.CardsGameServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cardsGame.CardsGameServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardsGameServer(object):
    """The service definition
    """

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardsGame.CardsGameServer/Connect',
            cardsGame__pb2.ConnectReq.SerializeToString,
            cardsGame__pb2.ConnectRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CardsGameSessionStub(object):
    """reason for this design: engine would return gameEvent as rsp to
    player´s move, which triggers onEvent on gameSession side.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeEvents = channel.unary_stream(
                '/cardsGame.CardsGameSession/SubscribeEvents',
                request_serializer=cardsGame__pb2.PlayerInfo.SerializeToString,
                response_deserializer=cardsGame__pb2.GameEventMsg.FromString,
                _registered_method=True)
        self.PlayMove = channel.unary_unary(
                '/cardsGame.CardsGameSession/PlayMove',
                request_serializer=cardsGame__pb2.PlayMoveReq.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CardsGameSessionServicer(object):
    """reason for this design: engine would return gameEvent as rsp to
    player´s move, which triggers onEvent on gameSession side.
    """

    def SubscribeEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlayMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CardsGameSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=cardsGame__pb2.PlayerInfo.FromString,
                    response_serializer=cardsGame__pb2.GameEventMsg.SerializeToString,
            ),
            'PlayMove': grpc.unary_unary_rpc_method_handler(
                    servicer.PlayMove,
                    request_deserializer=cardsGame__pb2.PlayMoveReq.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cardsGame.CardsGameSession', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cardsGame.CardsGameSession', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CardsGameSession(object):
    """reason for this design: engine would return gameEvent as rsp to
    player´s move, which triggers onEvent on gameSession side.
    """

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cardsGame.CardsGameSession/SubscribeEvents',
            cardsGame__pb2.PlayerInfo.SerializeToString,
            cardsGame__pb2.GameEventMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlayMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cardsGame.CardsGameSession/PlayMove',
            cardsGame__pb2.PlayMoveReq.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
